#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.prepend File.join(__dir__.to_s, '..', 'lib')

# Exit cleanly from an early interrupt
Signal.trap('INT') { exit 1 }

require 'fablicop'

Fablicop::CLI.start(ARGV)
