# inherit_gem中のexclude dirの指定が効かないらしい
# https://github.com/bbatsov/rubocop/issues/4154
# excludeしているものは一旦このファイルに直接記入

inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.3
