name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: version. The next release version (without prefix v)
        required: true
      apply:
        description: apply. Specify whether the actual release should be performed or not
        type: boolean
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{ secrets.FABLICOP_RELEASE_APP_ID }}
          private_key: ${{ secrets.FABLICOP_RELEASE_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.token.outputs.token }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true

      - name: Update `Fablicop::VERSION`
        run: |
          cat <<RUBY > lib/fablicop/version.rb
          # frozen_string_literal: true

          module Fablicop
            VERSION = '${{ github.event.inputs.version }}'
          end
          RUBY

      - run: git diff

      - uses: yykamei/actions-git-push@main
        with:
          commit-message: Bump to ${{ github.event.inputs.version }}
        if: github.event.inputs.apply == 'true'

      - run: gem build fablicop.gemspec

      - run: gem push ./*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        if: github.event.inputs.apply == 'true'

      - uses: yykamei/actions-release-actions@main
        with:
          tag: v${{ github.event.inputs.version }}
          apply: ${{ github.event.inputs.apply }}
          overwrite-major-minor: 'false'
